### ISSUE TITLE
Very interested in ember-elements

### ISSUE THREAD

**Issue by BryanHunt** [ember-elements/ember-elements#33]
This is more of an FYI rather than an issue since I realize you are just getting started - feel free to close.  I'm very interested in using ember-elements for a project I'm prototyping.  There are two components missing to get me started: Navbar and FormGroup.

As an aside, it would be nice if you had a roadmap so we could see which components are coming next.

**Comment by jugaadi** [comment]
Thanks @BryanHunt  for your feedback and excited to have you on board. Currently our project requirements drives the roadmap. The good news is that Navbar and FormGroup along with Tabs are in our immediate priorities. :raised_hands: 

We are also open to your suggestions in defining our roadmap. You can raise a request for a new component [here](https://github.com/dunkinbase/ember-elements/issues/new?assignees=jugaadi&labels=Type%3A+new+component+&template=new_component_request.md&title=New+component%3A+%3CSection%3E+-+%3CName%3E)

It would be great if you can also share your feedback on the API so that we can improve it further.
